(function () {
  const STORAGE_KEY = "selectedLanguage";

  const translations = {
    es: {
      "home.start": "Iniciar",
      "home.register": "Registrar",
      "login.title": "Inicio",
      "login.email_placeholder": "Correo",
      "login.password_placeholder": "Contraseña",
      "login.forgot": "¿Olvidó la contraseña?",
      "login.here": "aquí",
      "login.submit": "Iniciar",
      "login.no_account": "¿No tiene cuenta?",
      "login.register": "Regístrese",
      "register.title": "Registro",
      "register.user_placeholder": "Usuario",
      "register.email_placeholder": "Correo",
      "register.password_placeholder": "Contraseña",
      "register.confirm_placeholder": "Confirme Contraseña",
      "register.submit": "Registrarse",
      "register.has_account": "¿Ya tiene cuenta?",
      "register.login": "Inicie sesión",
      "recovery.title": "¿Olvidó su contraseña?",
      "recovery.description": "Ingrese el correo electrónico asociado a su cuenta y le enviaremos un enlace para restablecer su contraseña.",
      "recovery.email_placeholder": "Correo",
      "recovery.submit": "Enviar",
      "reset.title": "¿Olvidó su contraseña?",
      "reset.description": "Por favor, ingrese su nueva contraseña.",
      "reset.password_placeholder": "Contraseña",
      "reset.confirm_placeholder": "Confirmar Contraseña",
      "reset.requirement_1": "Debe tener al menos 8 caracteres.",
      "reset.requirement_2": "Debe incluir una letra mayúscula (A-Z).",
      "reset.requirement_3": "Debe incluir una letra minúscula (a-z).",
      "reset.requirement_4": "Debe incluir un número (0-9).",
      "reset.submit": "Enviar",
      "reset.back_login": "Volver al login",
      "feed.poly": "Sección Artificial/Poly",
      "feed.creative": "Sección Creativa",
      "feed.library": "Biblioteca",
      "feed.settings": "Configuraciones",
      "feed.start_question": "¿Qué comenzaremos hoy?",
      "feed.user": "Usuario:",
      "feed.email": "Correo:",
      "feed.models": "Modelos:",
      "feed.logout": "Cerrar Sesión",
      "settings.title": "Configuraciones",
      "settings.user": "Usuario",
      "settings.plan": "Plan:",
      "settings.profile": "Perfil",
      "settings.user_name": "Nombre Usuario:",
      "settings.email": "Correo:",
      "settings.joined": "Fecha de unión:",
      "settings.functions": "Funciones:",
      "settings.password": "Contraseña",
      "settings.change_password": "Cambiar Contraseña",
      "settings.delete_account": "Eliminar Cuenta",
      "settings.generals": "Generales",
      "settings.theme": "Tema:",
      "settings.notifications": "Notificación",
      "settings.language": "Idioma",
      "settings.instructions": "Instrucciones",
      "settings.ai_link": "AI (poly)",
      "settings.instructions_title": "Instrucciones",
      "settings.instructions_description": "Escribe aquí las reglas, tono o información que \"Poly\" debe recordar siempre en todos los chats",
      "settings.instructions_placeholder": "Respóndeme siempre en español.\nUsa un tono amigable y profesional.\nMi nombre de autor es \" \".\nNunca uses la palabra \"entonces\"",
      "settings.save": "Guardar",
      "settings.plans_title": "Planes de Suscripción",
      "settings.plans_subtitle": "Elige el plan que mejor se adapte a tus necesidades",
      "settings.free_plan": "Plan Gratuito",
      "settings.premium_plan": "Plan Premium",
      "common.active": "Activo",
      "common.available": "Disponible",
      "common.coming_soon": "💎 Próximamente",
      "library.title": "Biblioteca",
      "library.shelf_placeholder": "Nombre de la estantería",
      "library.new": "Nuevo",
      "library.shelves": "Estanterías",
      "shelves.title": "Estanterías",
      "shelves.empty": "Aún no tienes estanterías",
      "shelves.open": "Abrir",
      "shelves.rename": "Renombrar",
      "shelves.delete": "Eliminar",
      "shelves.rename_prompt": "Nuevo nombre de la estantería",
      "shelves.delete_confirm": "¿Eliminar esta estantería?"
    },
    en: {
      "home.start": "Sign in",
      "home.register": "Register",
      "login.title": "Sign in",
      "login.email_placeholder": "Email",
      "login.password_placeholder": "Password",
      "login.forgot": "Forgot your password?",
      "login.here": "here",
      "login.submit": "Sign in",
      "login.no_account": "Don't have an account?",
      "login.register": "Register",
      "register.title": "Register",
      "register.user_placeholder": "Username",
      "register.email_placeholder": "Email",
      "register.password_placeholder": "Password",
      "register.confirm_placeholder": "Confirm Password",
      "register.submit": "Register",
      "register.has_account": "Already have an account?",
      "register.login": "Sign in",
      "recovery.title": "Forgot your password?",
      "recovery.description": "Enter the email associated with your account and we will send you a link to reset your password.",
      "recovery.email_placeholder": "Email",
      "recovery.submit": "Send",
      "reset.title": "Forgot your password?",
      "reset.description": "Please enter your new password.",
      "reset.password_placeholder": "Password",
      "reset.confirm_placeholder": "Confirm Password",
      "reset.requirement_1": "It must be at least 8 characters long.",
      "reset.requirement_2": "It must include one uppercase letter (A-Z).",
      "reset.requirement_3": "It must include one lowercase letter (a-z).",
      "reset.requirement_4": "It must include one number (0-9).",
      "reset.submit": "Send",
      "reset.back_login": "Back to login",
      "feed.poly": "Artificial Section/Poly",
      "feed.creative": "Creative Section",
      "feed.library": "Library",
      "feed.settings": "Settings",
      "feed.start_question": "What will we start today?",
      "feed.user": "User:",
      "feed.email": "Email:",
      "feed.models": "Models:",
      "feed.logout": "Log out",
      "settings.title": "Settings",
      "settings.user": "User",
      "settings.plan": "Plan:",
      "settings.profile": "Profile",
      "settings.user_name": "Username:",
      "settings.email": "Email:",
      "settings.joined": "Join date:",
      "settings.functions": "Functions:",
      "settings.password": "Password",
      "settings.change_password": "Change Password",
      "settings.delete_account": "Delete Account",
      "settings.generals": "General",
      "settings.theme": "Theme:",
      "settings.notifications": "Notifications",
      "settings.language": "Language",
      "settings.instructions": "Instructions",
      "settings.ai_link": "AI (poly)",
      "settings.instructions_title": "Instructions",
      "settings.instructions_description": "Write the rules, tone or information that \"Poly\" should always remember in every chat",
      "settings.instructions_placeholder": "Always answer me in English.\nUse a friendly and professional tone.\nMy author name is \" \".\nNever use the word \"then\"",
      "settings.save": "Save",
      "settings.plans_title": "Subscription Plans",
      "settings.plans_subtitle": "Choose the plan that best fits your needs",
      "settings.free_plan": "Free Plan",
      "settings.premium_plan": "Premium Plan",
      "common.active": "Active",
      "common.available": "Available",
      "common.coming_soon": "💎 Coming soon",
      "library.title": "Library",
      "library.shelf_placeholder": "Shelf name",
      "library.new": "New",
      "library.shelves": "Shelves",
      "shelves.title": "Shelves",
      "shelves.empty": "You don't have shelves yet",
      "shelves.open": "Open",
      "shelves.rename": "Rename",
      "shelves.delete": "Delete",
      "shelves.rename_prompt": "New shelf name",
      "shelves.delete_confirm": "Delete this shelf?"
    },
    de: {
      "home.start": "Anmelden",
      "home.register": "Registrieren",
      "login.title": "Anmelden",
      "login.email_placeholder": "E-Mail",
      "login.password_placeholder": "Passwort",
      "login.forgot": "Passwort vergessen?",
      "login.here": "hier",
      "login.submit": "Anmelden",
      "login.no_account": "Noch kein Konto?",
      "login.register": "Registrieren",
      "register.title": "Registrierung",
      "register.user_placeholder": "Benutzername",
      "register.email_placeholder": "E-Mail",
      "register.password_placeholder": "Passwort",
      "register.confirm_placeholder": "Passwort bestätigen",
      "register.submit": "Registrieren",
      "register.has_account": "Hast du bereits ein Konto?",
      "register.login": "Anmelden",
      "recovery.title": "Passwort vergessen?",
      "recovery.description": "Gib die E-Mail deiner Kontos ein und wir senden dir einen Link zum Zurücksetzen deines Passworts.",
      "recovery.email_placeholder": "E-Mail",
      "recovery.submit": "Senden",
      "reset.title": "Passwort vergessen?",
      "reset.description": "Bitte gib dein neues Passwort ein.",
      "reset.password_placeholder": "Passwort",
      "reset.confirm_placeholder": "Passwort bestätigen",
      "reset.requirement_1": "Es muss mindestens 8 Zeichen lang sein.",
      "reset.requirement_2": "Es muss einen Großbuchstaben (A-Z) enthalten.",
      "reset.requirement_3": "Es muss einen Kleinbuchstaben (a-z) enthalten.",
      "reset.requirement_4": "Es muss eine Zahl (0-9) enthalten.",
      "reset.submit": "Senden",
      "reset.back_login": "Zurück zum Login",
      "feed.poly": "Künstlicher Bereich/Poly",
      "feed.creative": "Kreativer Bereich",
      "feed.library": "Bibliothek",
      "feed.settings": "Einstellungen",
      "feed.start_question": "Womit beginnen wir heute?",
      "feed.user": "Benutzer:",
      "feed.email": "E-Mail:",
      "feed.models": "Modelle:",
      "feed.logout": "Abmelden",
      "settings.title": "Einstellungen",
      "settings.user": "Benutzer",
      "settings.plan": "Plan:",
      "settings.profile": "Profil",
      "settings.user_name": "Benutzername:",
      "settings.email": "E-Mail:",
      "settings.joined": "Beitrittsdatum:",
      "settings.functions": "Funktionen:",
      "settings.password": "Passwort",
      "settings.change_password": "Passwort ändern",
      "settings.delete_account": "Konto löschen",
      "settings.generals": "Allgemein",
      "settings.theme": "Thema:",
      "settings.notifications": "Benachrichtigung",
      "settings.language": "Sprache",
      "settings.instructions": "Anweisungen",
      "settings.ai_link": "KI (poly)",
      "settings.instructions_title": "Anweisungen",
      "settings.instructions_description": "Schreibe hier die Regeln, den Ton oder die Informationen, an die sich \"Poly\" in jedem Chat erinnern soll",
      "settings.instructions_placeholder": "Antworte mir immer auf Deutsch.\nVerwende einen freundlichen und professionellen Ton.\nMein Autorenname ist \" \".\nVerwende niemals das Wort \"dann\"",
      "settings.save": "Speichern",
      "settings.plans_title": "Abonnementpläne",
      "settings.plans_subtitle": "Wähle den Plan, der am besten zu dir passt",
      "settings.free_plan": "Kostenloser Plan",
      "settings.premium_plan": "Premium-Plan",
      "common.active": "Aktiv",
      "common.available": "Verfügbar",
      "common.coming_soon": "💎 Bald verfügbar",
      "library.title": "Bibliothek",
      "library.shelf_placeholder": "Regalname",
      "library.new": "Neu",
      "library.shelves": "Regale",
      "shelves.title": "Regale",
      "shelves.empty": "Du hast noch keine Regale",
      "shelves.open": "Öffnen",
      "shelves.rename": "Umbenennen",
      "shelves.delete": "Löschen",
      "shelves.rename_prompt": "Neuer Regalname",
      "shelves.delete_confirm": "Dieses Regal löschen?"
    },
    fr: {
      "home.start": "Connexion",
      "home.register": "S'inscrire",
      "login.title": "Connexion",
      "login.email_placeholder": "E-mail",
      "login.password_placeholder": "Mot de passe",
      "login.forgot": "Mot de passe oublié ?",
      "login.here": "ici",
      "login.submit": "Connexion",
      "login.no_account": "Vous n'avez pas de compte ?",
      "login.register": "S'inscrire",
      "register.title": "Inscription",
      "register.user_placeholder": "Nom d'utilisateur",
      "register.email_placeholder": "E-mail",
      "register.password_placeholder": "Mot de passe",
      "register.confirm_placeholder": "Confirmer le mot de passe",
      "register.submit": "S'inscrire",
      "register.has_account": "Vous avez déjà un compte ?",
      "register.login": "Se connecter",
      "recovery.title": "Mot de passe oublié ?",
      "recovery.description": "Entrez l'e-mail associé à votre compte et nous vous enverrons un lien pour réinitialiser votre mot de passe.",
      "recovery.email_placeholder": "E-mail",
      "recovery.submit": "Envoyer",
      "reset.title": "Mot de passe oublié ?",
      "reset.description": "Veuillez saisir votre nouveau mot de passe.",
      "reset.password_placeholder": "Mot de passe",
      "reset.confirm_placeholder": "Confirmer le mot de passe",
      "reset.requirement_1": "Il doit contenir au moins 8 caractères.",
      "reset.requirement_2": "Il doit inclure une lettre majuscule (A-Z).",
      "reset.requirement_3": "Il doit inclure une lettre minuscule (a-z).",
      "reset.requirement_4": "Il doit inclure un chiffre (0-9).",
      "reset.submit": "Envoyer",
      "reset.back_login": "Retour à la connexion",
      "feed.poly": "Section Artificielle/Poly",
      "feed.creative": "Section Créative",
      "feed.library": "Bibliothèque",
      "feed.settings": "Paramètres",
      "feed.start_question": "Par quoi commençons-nous aujourd'hui ?",
      "feed.user": "Utilisateur :",
      "feed.email": "E-mail :",
      "feed.models": "Modèles :",
      "feed.logout": "Déconnexion",
      "settings.title": "Paramètres",
      "settings.user": "Utilisateur",
      "settings.plan": "Plan :",
      "settings.profile": "Profil",
      "settings.user_name": "Nom d'utilisateur :",
      "settings.email": "E-mail :",
      "settings.joined": "Date d'inscription :",
      "settings.functions": "Fonctions :",
      "settings.password": "Mot de passe",
      "settings.change_password": "Changer le mot de passe",
      "settings.delete_account": "Supprimer le compte",
      "settings.generals": "Général",
      "settings.theme": "Thème :",
      "settings.notifications": "Notifications",
      "settings.language": "Langue",
      "settings.instructions": "Instructions",
      "settings.ai_link": "IA (poly)",
      "settings.instructions_title": "Instructions",
      "settings.instructions_description": "Écrivez ici les règles, le ton ou les informations que \"Poly\" doit toujours retenir dans tous les chats",
      "settings.instructions_placeholder": "Réponds-moi toujours en français.\nUtilise un ton amical et professionnel.\nMon nom d'auteur est \" \".\nN'utilise jamais le mot \"alors\"",
      "settings.save": "Enregistrer",
      "settings.plans_title": "Plans d'abonnement",
      "settings.plans_subtitle": "Choisissez le plan qui correspond le mieux à vos besoins",
      "settings.free_plan": "Plan Gratuit",
      "settings.premium_plan": "Plan Premium",
      "common.active": "Actif",
      "common.available": "Disponible",
      "common.coming_soon": "💎 Bientôt disponible",
      "library.title": "Bibliothèque",
      "library.shelf_placeholder": "Nom de l'étagère",
      "library.new": "Nouveau",
      "library.shelves": "Étagères",
      "shelves.title": "Étagères",
      "shelves.empty": "Vous n'avez pas encore d'étagères",
      "shelves.open": "Ouvrir",
      "shelves.rename": "Renommer",
      "shelves.delete": "Supprimer",
      "shelves.rename_prompt": "Nouveau nom de l'étagère",
      "shelves.delete_confirm": "Supprimer cette étagère ?"
    },
    ja: {
      "home.start": "ログイン",
      "home.register": "登録",
      "login.title": "ログイン",
      "login.email_placeholder": "メール",
      "login.password_placeholder": "パスワード",
      "login.forgot": "パスワードをお忘れですか？",
      "login.here": "こちら",
      "login.submit": "ログイン",
      "login.no_account": "アカウントをお持ちでありませんか？",
      "login.register": "登録する",
      "register.title": "登録",
      "register.user_placeholder": "ユーザー名",
      "register.email_placeholder": "メール",
      "register.password_placeholder": "パスワード",
      "register.confirm_placeholder": "パスワード確認",
      "register.submit": "登録する",
      "register.has_account": "すでにアカウントをお持ちですか？",
      "register.login": "ログイン",
      "recovery.title": "パスワードをお忘れですか？",
      "recovery.description": "アカウントに関連付けられたメールアドレスを入力すると、パスワード再設定用のリンクを送信します。",
      "recovery.email_placeholder": "メール",
      "recovery.submit": "送信",
      "reset.title": "パスワードをお忘れですか？",
      "reset.description": "新しいパスワードを入力してください。",
      "reset.password_placeholder": "パスワード",
      "reset.confirm_placeholder": "パスワード確認",
      "reset.requirement_1": "8文字以上である必要があります。",
      "reset.requirement_2": "大文字 (A-Z) を1文字含めてください。",
      "reset.requirement_3": "小文字 (a-z) を1文字含めてください。",
      "reset.requirement_4": "数字 (0-9) を1文字含めてください。",
      "reset.submit": "送信",
      "reset.back_login": "ログインに戻る",
      "feed.poly": "AI セクション/Poly",
      "feed.creative": "クリエイティブセクション",
      "feed.library": "ライブラリ",
      "feed.settings": "設定",
      "feed.start_question": "今日は何から始めますか？",
      "feed.user": "ユーザー:",
      "feed.email": "メール:",
      "feed.models": "モデル:",
      "feed.logout": "ログアウト",
      "settings.title": "設定",
      "settings.user": "ユーザー",
      "settings.plan": "プラン:",
      "settings.profile": "プロフィール",
      "settings.user_name": "ユーザー名:",
      "settings.email": "メール:",
      "settings.joined": "登録日:",
      "settings.functions": "機能:",
      "settings.password": "パスワード",
      "settings.change_password": "パスワード変更",
      "settings.delete_account": "アカウント削除",
      "settings.generals": "一般",
      "settings.theme": "テーマ:",
      "settings.notifications": "通知",
      "settings.language": "言語",
      "settings.instructions": "指示",
      "settings.ai_link": "AI (poly)",
      "settings.instructions_title": "指示",
      "settings.instructions_description": "\"Poly\" がすべてのチャットで常に覚えておくべきルール、口調、情報をここに書いてください",
      "settings.instructions_placeholder": "常に日本語で答えてください。\n親しみやすく丁寧な口調を使ってください。\n私の著者名は \" \" です。\n「それでは」という言葉は使わないでください",
      "settings.save": "保存",
      "settings.plans_title": "サブスクリプションプラン",
      "settings.plans_subtitle": "あなたに最適なプランを選んでください",
      "settings.free_plan": "無料プラン",
      "settings.premium_plan": "プレミアムプラン",
      "common.active": "有効",
      "common.available": "利用可能",
      "common.coming_soon": "💎 近日公開",
      "library.title": "ライブラリ",
      "library.shelf_placeholder": "棚の名前",
      "library.new": "新規",
      "library.shelves": "本棚",
      "shelves.title": "本棚",
      "shelves.empty": "まだ本棚がありません",
      "shelves.open": "開く",
      "shelves.rename": "名前変更",
      "shelves.delete": "削除",
      "shelves.rename_prompt": "新しい本棚の名前",
      "shelves.delete_confirm": "この本棚を削除しますか？"
    }
  };

  const getCurrentLanguage = () => localStorage.getItem(STORAGE_KEY) || "es";

  const translate = (key, language = getCurrentLanguage()) => {
    const selected = translations[language] || translations.es;
    return selected[key] || translations.es[key] || key;
  };

  const applyTranslations = (root = document) => {
    const language = getCurrentLanguage();
    document.documentElement.lang = language;

    root.querySelectorAll("[data-i18n]").forEach((element) => {
      element.textContent = translate(element.dataset.i18n, language);
    });

    root.querySelectorAll("[data-i18n-placeholder]").forEach((element) => {
      element.placeholder = translate(element.dataset.i18nPlaceholder, language);
    });
  };

  const setLanguage = (language) => {
    const normalized = translations[language] ? language : "es";
    localStorage.setItem(STORAGE_KEY, normalized);
    applyTranslations();
    window.dispatchEvent(
      new CustomEvent("languagechange", {
        detail: { language: normalized },
      }),
    );
  };

  window.languageManager = {
    getCurrentLanguage,
    translate,
    applyTranslations,
    setLanguage,
  };

  document.addEventListener("DOMContentLoaded", () => {
    applyTranslations();
  });
})();
